version: '3.8'

services:
  janggi-server:
    build: .
    container_name: janggi-server
    ports:
      - "8001:8001" # 호스트 8001 <-> 컨테이너 8001
    volumes:
      # 로그 파일 등을 호스트와 공유하고 싶다면 사용
      - ./logs:/app/logs
    environment:
      - FAIRY_STOCKFISH_PATH=/app/bin/fairy-stockfish
      # Prod/Dev 환경 변수 추가 가능
      # - ENV=production
    restart: always
