version: '3.8'

services:
  janggi:
    build: .
    container_name: server
    ports:
      - "8001:8001" # 호스트 8001 <-> 컨테이너 8001
    volumes:
      # 로그 파일 등을 호스트와 공유하고 싶다면 사용
      - ./logs:/app/logs
    environment:
      - FAIRY_STOCKFISH_PATH=/app/bin/fairy-stockfish
      - APP_ENV=production
    restart: always
